apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: auth-
# Base configuration
resources:
  - ../../../base # Inherits common deployment, service, and ingress configurations

# Patches to override base config
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml

      
# Namespace definition (ensures the namespace exists)
# namespace: staging

# Generate ConfigMaps
# configMapGenerator:
#   - name: service1-config
#     literals:
#       - ENV=staging
#       - LOG_LEVEL=debug
